version: "3.9"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules # Ignore host node_modules
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: backend-service
    env_file:
      - ./backend/.env
    command: npm run start
    networks:
      - mern-network

  frontend:
    volumes:
      - ./frontend/counter-frontend:/app
      - /app/node_modules # Ignore host node_modules
    build:
      context: ./frontend/counter-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    container_name: frontend-service
    depends_on:
      - backend
    command: npm run dev -- --host
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
